chore: Update build_frontend.yml to use "/var/www/html" as the target directory for deployment

diff --git a/.github/workflows/build_frontend.yml b/.github/workflows/build_frontend.yml
--- a/.github/workflows/build_frontend.yml
+++ b/.github/workflows/build_frontend.yml
@@ -42,46 +42,46 @@ jobs:
       #   runs-on: ubuntu-latest
 
       #   steps:
-      # - name: log files
-      #   run: ls -la .
+      - name: log files
+        run: ls -la .
 
-      # - name: log files
-      #   run: ls -la ./dist/
+      - name: log files
+        run: ls -la ./dist/
 
-      # - name: pwd
-      #   run: pwd
+      - name: pwd
+        run: pwd
 
-      # - name: deploy angular app
-      #   uses: appleboy/scp-action@master
-      #   with:
-      #     host: ${{ secrets.VPS_HOST }}
-      #     username: ${{ secrets.VPS_USERNAME }}
-      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
-      #     port: ${{ secrets.VPS_PORT }}
-      #     source: "./dist/*"
-      #     target: "/var/www/html"
-      #     strip_components: 1
-      #     rm: true
-
-      - name: 📤 Deploy to VPS
-        uses: easingthemes/ssh-deploy@main
+      - name: deploy angular app
+        uses: appleboy/scp-action@master
         with:
-          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-          ARGS: "-azrut --delete"
-          SOURCE: "dist/"
-          REMOTE_HOST: ${{ secrets.VPS_HOST }}
-          REMOTE_USER: ${{ secrets.VPS_USERNAME }}
-          REMOTE_PORT: ${{ secrets.VPS_PORT }}
-          TARGET: "/var/www/html"
-          SCRIPT_BEFORE: |
-            if ! command -v rsync &> /dev/null
-            then
-              echo "rsync could not be found, installing..."
-              sudo apt-get update
-              sudo apt-get install -y rsync
-            else
-              echo "rsync is already installed."
-            fi
-            echo "Starting deployment..."
-          SCRIPT_AFTER: |
-            echo "Vue.js app deployed successfully!"
+          host: ${{ secrets.VPS_HOST }}
+          username: ${{ secrets.VPS_USERNAME }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          port: ${{ secrets.VPS_PORT }}
+          source: "./frontend/dist/*"
+          target: "/var/www/html"
+          strip_components: 1
+          rm: true
+
+      # - name: 📤 Deploy to VPS
+      #   uses: easingthemes/ssh-deploy@main
+      #   with:
+      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+      #     ARGS: "-azrut --delete"
+      #     SOURCE: "dist/"
+      #     REMOTE_HOST: ${{ secrets.VPS_HOST }}
+      #     REMOTE_USER: ${{ secrets.VPS_USERNAME }}
+      #     REMOTE_PORT: ${{ secrets.VPS_PORT }}
+      #     TARGET: "/var/www/html"
+      #     SCRIPT_BEFORE: |
+      #       if ! command -v rsync &> /dev/null
+      #       then
+      #         echo "rsync could not be found, installing..."
+      #         sudo apt-get update
+      #         sudo apt-get install -y rsync
+      #       else
+      #         echo "rsync is already installed."
+      #       fi
+      #       echo "Starting deployment..."
+      #     SCRIPT_AFTER: |
+      #       echo "Vue.js app deployed successfully!"
